version: "3"
services:
  api:
    build:
      context: . #Build Dockerfile 
    container_name: "flask_clp"
    # volumes:
    #   - db-file-volumn:/app/db_file
    #   - service-volumn:/app/log
    ports:
      - 5000:5000
    networks: 
      - clp_network
    restart: always
# volumes:
#   service-volumn:
#   db-file-volumn:
networks:
    clp_network:
        external: true    